name: AnitAlts2
main: com.jaoafa.AntiAlts2.AntiAlts2
version: 0.0.1
description: サブアカウントのログイン関連を制御するプラグイン
database: true
softdepend: [PermissionsEx, LuckPerms]
author: mine_book000
commands:
   alts:
      description: このプラグインに関する設定や情報が確認できます。
      usage: /<command>
      permission: periodmatch.period
permission-message: You do not have permission to perform this command.